services:
  captioner:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      IMAGE_SIZE: 256
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
